blank_issues_enabled: true
contact_links:
  - name: Join the CNCF TOC mailing list
    url: https://lists.cncf.io/g/cncf-toc
    about: Join the public mailing list around CNCF Technical Oversight Committee (TOC)
  - name: See the TOC Project Board Backlog
    url: https://github.com/orgs/cncf/projects/27
    about: View the current backlog of projects + TOC Work
